baseURL = "https://acrimed-nantes.org/"
DefaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Acrimed Nantes"
theme = "acrimed"
description = "Site de l'antenne locale d'Acrimed Nantes. Retrouvez nos articles, les événéments et les ateliers proposés par Acrimed Nantes."

[[menu.main]]
  name = "Accueil"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Événement"
  weight = 2
  identifier = "event"
  url = "/evenement/"
[[menu.main]]
  name = "Article"
  weight = 3
  identifier = "article"
  url = "/article/"

[taxonomies]
  tag = "tags"
